language: python
python:
  - "2.6"
  - "2.7"
before_script:
  - sudo apt-get install python-coverage 
  - sudo apt-get install pychecker
  - sudo apt-get install pymetrics
  - sudo apt-get install python-setuptools
  - sudo apt-get install pylint
  - sudo easy_install http://python-builder.googlecode.com/files/python-builder-0.6.2.tar.gz
script: "pyb"
notifications:
  email:
  - aelgru@gmail.com
