language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "pypy"
before_script: sudo apt-get install pychecker pylint pep8
install: pip install -r requirements.txt --use-mirrors
script: "pyb --debug"
notifications:
  email:
  - aelgru@gmail.com
