language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
before_script: sudo apt-get install pychecker pylint pep8
install: pip install -r requirements.txt --use-mirrors
script: "pyb"
notifications:
  email:
  - aelgru@gmail.com
