language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
before_script:
  - sudo apt-get install python-coverage 
  - sudo apt-get install pychecker
  - sudo apt-get install pymetrics
  - sudo apt-get install python-setuptools
  - sudo apt-get install pylint
  - sudo pip install https://github.com/downloads/pybuilder/pybuilder/pybuilder-0.7.1.tar.gz
script: "pyb"
notifications:
  email:
  - aelgru@gmail.com
