#!/usr/bin/env python
#
#   Copyright 2012, Michael Gruber
#   Licensed under Apache License, Version 2.0

"""
    Script to support iterative and incremental work with repositories.
"""

import committer
import sys


arguments = sys.argv
committer.main(arguments)