#!/usr/bin/env python
#
#   committer
#   Copyright 2012 Michael Gruber
#   
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#   
#       http://www.apache.org/licenses/LICENSE-2.0
#   
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

"""
    Committer provides a simplified command line interface to the version
    control systems git, mercurial, and subversion.
    By executing the "update" script you will update the repository in the
    current directory. Try "commit" if you want to commit.
    
    usage:
        update
"""

__author__ = 'Michael Gruber'

import sys

from committer import perform, update

perform(update, sys.argv, __doc__)
